### PR TITLE
Added BT Traversal code

### PR DESCRIPTION
**Pull request by MdAsimKhan**

### CODE REVIEW

**Comment by janusjerom** [comment]
Please add your Name and Program name as the first two lines. Please refer to CONTRIBUTING.md for more details.

**Comment by MdAsimKhan** [comment]
Is it okay if I add name and program name in a .txt file?

**Comment by MdAsimKhan** [comment]
I have added my name and the program name, please review it and kindly merge my pull request.

**Comment by janusjerom** [comment]
Yes great PR !!

**Pull request merged**
